@echo off
cd /d "c:\Users\yerko\agentes"
echo 🗓️ Iniciando Agente Agenda...
C:\Users\yerko\AppData\Local\Programs\Python\Python312\python.exe trinity_agenda.py
echo 📈 Iniciando Agente Semanal...
C:\Users\yerko\AppData\Local\Programs\Python\Python312\python.exe trinity_semanal.py
echo 📡 Iniciando Agente Radar IA...
C:\Users\yerko\AppData\Local\Programs\Python\Python312\python.exe trinity_radar.py
echo 📧 Iniciando Agente Correo Diario...
C:\Users\yerko\AppData\Local\Programs\Python\Python312\python.exe trinity_correo.py
echo ✅ Reportes matutinos completados.
